# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      run: npm i -g pnpm
    
    - name: Install dependencies
      run: pnpm install
      
    - name: Build application
      run: pnpm run build

    - name: Install Vercel CLI
      run: npm i -g vercel
    
    - name: Show value in variable
      run: echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}"
  
    - name: Deploy to Vercel
      run: |
          vercel deploy --prod \
            --token ${{ secrets.VERCEL_TOKEN }} \
            -y